version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django_portfolio
    ports:
      - 8000:8000
    image: app:django_portfolio
    container_name: portfolio_container
    command: python3 portfolio_website/manage.py runserver 0.0.0.0:8000